# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaccount',
            options={'permissions': (('list_clientaccount', 'List Client Account'), ('view_clientaccount', 'View Client Account')), 'verbose_name': 'Client Account', 'verbose_name_plural': 'Client Accounts'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'permissions': (('list_entity', 'List Entity'), ('view_entity', 'View Entity')), 'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
    ]
