# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 22:14
from __future__ import unicode_literals

import django.core.validators
import contacts.models
import catalog.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20161001_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='identification',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(b'^\\d*$')], verbose_name='Identification'),
        ),
        migrations.AddField(
            model_name='entity',
            name='identification_country',
            field=catalog.fields.CatalogFK(default=contacts.models.default_country, on_delete=django.db.models.deletion.CASCADE, to='contacts.EntityCountry', to_field=b'code'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=set([('identification_country', 'identification')]),
        ),
    ]
