# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 22:42
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils.translation import ugettext_lazy as _
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20161001_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='provider',
            field=models.BooleanField(default=False, verbose_name=_('Is Provider')),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_accounts', to='contacts.Entity', verbose_name='Entity'),
        ),
    ]
