# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 23:02
from __future__ import unicode_literals

import catalog.fields
import contacts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20161001_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='identification_country',
            field=catalog.fields.CatalogFK(default=contacts.models.default_country, on_delete=django.db.models.deletion.CASCADE, to='contacts.EntityCountry', to_field=b'code', verbose_name='Identification Country'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='identification_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Citizen ID'), (2, 'Passport')], default=1, verbose_name='Identification Type'),
        ),
    ]
