# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-01 23:55
from __future__ import unicode_literals

import catalog.fields
import contacts.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_entity_identification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='identification_country',
            field=catalog.fields.CatalogFK(default=contacts.models.default_country, on_delete=django.db.models.deletion.PROTECT, to='contacts.EntityCountry', to_field=b'code', verbose_name='Identification Country'),
        ),
    ]
