# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20161001_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientaccount',
            options={'permissions': (('list_clientaccount', 'Can list Client Account'), ('view_clientaccount', 'Can view Client Account')), 'verbose_name': 'Client Account', 'verbose_name_plural': 'Client Accounts'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'permissions': (('list_entity', 'Can list Entity'), ('view_entity', 'Can view Entity')), 'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
    ]
