# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20170115_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitycountry',
            options={'verbose_name': 'Entity Country', 'verbose_name_plural': 'Entity Countries'},
        ),
    ]
