# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packaging',
            options={'permissions': (('list_packaging', 'Can list Packaging'), ('view_packaging', 'Can view Packaging')), 'verbose_name': 'Packaging', 'verbose_name_plural': 'Packagings'},
        ),
        migrations.AlterModelOptions(
            name='rawmaterial',
            options={'permissions': (('list_rawmaterial', 'Can list Raw Material'), ('view_rawmaterial', 'Can view Raw Material')), 'verbose_name': 'Raw Material', 'verbose_name_plural': 'Raw Materials'},
        ),
        migrations.AlterModelOptions(
            name='workforce',
            options={'permissions': (('list_workforce', 'Can list Work Force'), ('view_workforce', 'Can view Work Force')), 'verbose_name': 'Work Force', 'verbose_name_plural': 'Work Forces'},
        ),
    ]
