# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 04:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20170115_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packaging',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='kg_price',
            field=models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Price per Kg'),
        ),
        migrations.AlterField(
            model_name='workforce',
            name='hourly_price',
            field=models.DecimalField(decimal_places=3, max_digits=7, validators=[django.core.validators.MinValueValidator(0.001)], verbose_name='Hourly Price'),
        ),
    ]
