"""
Django settings for quimelia_gestion project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l437nydgpwfq+!083pw6xjq0^m^fe3t)uw3m&x5e896(k!*266'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = ['gestion.quimelia.com.ec', 'gestion.quimelia.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    'polymorphic',
    'grimoire.django.xmail',
    'grimoire.django.dynsettings',
    'grimoire.django.tracked',
    'geo',
    'main'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'quimelia_gestion.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'UNICODE_JSON': False,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

WSGI_APPLICATION = 'quimelia_gestion.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'quimelia_gestion',
        'USER': 'quimelia',
        'PASSWORD': 'mysql:quimelia$2015',
        'HOST': 'localhost',
    }
}

# Login-related urls

LOGIN_REDIRECT_URL = 'main:index'
LOGIN_URL = 'main:login'

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'es-ec'
TIME_ZONE = 'America/Guayaquil'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = 'http://static.quimelia.com.ec/quimelia_gestion/'
STATIC_ROOT = '/home/rleiva/webapps/static/quimelia_gestion/'
MEDIA_URL = 'http://media.quimelia.com.ec/quimelia_gestion/'
MEDIA_ROOT = '/home/rleiva/webapps/media/quimelia_gestion/'

# TODO mailing - cuando se necesite

# EMAIL_HOST = 'smtp.infodataec.com'
# EMAIL_PORT = 25
# EMAIL_HOST_USER = 'notifications_infodataec'
# EMAIL_HOST_PASSWORD = 'notifications$infodataec$2016'
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = False
EMAIL_BACKEND = 'grimoire.django.xmail.backends.AsyncEmailBackend'
XMAIL_BRIDGED_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Importing local settings

try:
    from local_settings import *
except ImportError:
    pass